runtime: python39
entrypoint: python3 bot.py

instance_class: F2

env_variables:
  TOKEN: '6621746807:AAGZfLtnH-e8KOObiBT48atMKTnLSRtqusE'
  GOOGLE_APPLICATION_CREDENTIALS: '/tmp/my-google-credentials.json'

handlers:
- url: /.*
  script: auto
